config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :listing

  get '/listing/:sokeord', to: 'listing#index'

  get 'profile', to: 'profile#show'
  get 'profile/:id', to: 'profile#show'

  get '/.well-known/acme-challenge/:id', to: 'static_page#acme'

  authenticated do
    root to: 'listing#index', as: :authenticated_root
  end

  root to: 'static_page#index'

  #static_page
  get '/about', action: :index, controller: :static_page
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :title, :description, :price, presence: true

  validates :title, length: { minimum: 2, maximum: 50 }

  validates :description, length: { minimum: 2, maximum: 400 }

  validates :price, numericality: { only_integer: true, minimum: 0,
                                    greater_than: 0,
                                    less_than_or_equal_to: 1_000_000 }

  validates :user, presence: true

  validate :validate_number_of_images

  belongs_to :user

  # image uploading
  mount_uploaders :listingimages, ListingImagesUploader

  def validate_number_of_images
    unless listingimages.count <= 5
      errors.add(:listingimages, "maks 5 bilder per annonse")
    end
  end

  def self.search(search_query, current_page)
    if search_query
      where('title ~* ? OR description ~* ?', search_query, search_query).paginate(page: current_page, per_page: 12).order('id DESC')
    else
      paginate(page: current_page, per_page: 12).order('id DESC')
    end
  end
end

app/models/user.rb
# Main user, used for auth
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, length: { minimum: 1, maximum: 30 },
    format: { with: /\A[æøå\w\-\'\s]+\z/ }

  validates :last_name, length: { minimum: 1, maximum: 30 },
    format: { with: /\A[æøå\w\-\'\s]+\z/ }

  validates :place_id, :location, length: { minimum: 1, maximum: 100 }

  validates :telephone, length: { minimum: 8, maximum: 14 },
    format: { with: /\A(\+\d{2}\s)?[\d\s]{8,10}\z/ }

  has_many :listings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/listing_controller.rb
require 'json'
require 'net/http'

class ListingController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @listings = Listing.search(params[:sokeord], params[:side])
    @search_query = params[:sokeord]
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user

    if @listing.save
      redirect_to listing_path(@listing), notice: 'Annonsen din er publisert'
    else
      render 'new'
    end
  end

  def destroy
    listing = Listing.find_by(id: params['id'])

    unless listing
      return redirect_to listing_index_path, notice: 'Den annonsen finnes ikke'
    end

    if listing.user == current_user || current_user.admin
      listing.destroy
      return redirect_to listing_index_path, notice: 'Annonsen ble slettet'
    else
      return redirect_to listing_path(listing),
                         error: 'Du har ikke rettigheter til dette'
    end
  end

  def edit
    @listing = Listing.find_by(id: params[:id])

    unless @listing
      return redirect_to listing_index_path, notice: 'Den annonsen finnes ikke'
    end

    unless @listing.user == current_user
      return redirect_to listing_path(@listing), notice: 'Du eier ikke denne annonsen'
    end
  end

  def update
    @listing = Listing.find_by(id: params[:id])

    unless @listing
      return redirect_to listing_index_path, notice: 'Den annonsen finnes ikke'
    end

    unless @listing.user == current_user
      return redirect_to listing_path(@listing),
        notice: 'Du er ikke autorisert til å gjøre endringer til denne annonsen'
    end

    if @listing.update_attributes(listing_params)
      redirect_to listing_path(@listing), notice: 'Din annonse har blitt endret'
    else
      render 'edit'
    end
  end

  def show
    @listing = Listing.find_by(id: params['id'])

    unless @listing
      return redirect_to listing_index_path, notice: 'Den annonsen finnes ikke'
    end
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :description, :price,
                                    { listingimages: [] })
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
    if params[:id]
      @user = User.find_by(id: params[:id])
    else
      if user_signed_in?
        @user = current_user
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :telephone,
                                 :password, :password_confirmation,
                                 :place_id, :location)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :telephone,
                                 :current_password, :password_confirmation,
                                 :place_id, :location)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
  end

  def acme
    render text: ''
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(user)
    "#{user.first_name} #{user.last_name}"
  end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='no'>
  <head>
    <title>Leiestedet</title>
    <%= csrf_meta_tags %>

    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>&libraries=places&callback=initMap" async defer></script>
    <%= favicon_link_tag %>
  </head>

  <body>
    <% if controller_name != 'static_page' %>
      <div class="footer-compliant-body">
      <% end %>
      <div <% if controller_name == 'static_page' %>class='navbar-fixed'<% end %>>
        <%= render partial: 'shared/navigation' %>
      </div>

      <% if controller_name != 'static_page' %>
        <div class="footer-compliant-body">
          <div class="container flex-container">
          <% end %>

          <%= yield %>

          <% if controller_name != 'static_page' %>
            </div>
          <% end %>

          <%= render partial: 'shared/footer' %>
          <% if controller_name != 'static_page' %>
          </div>
        <% end %>

        <script>
<% flash.each do |key, value| %>
  Materialize.toast("<%= value %>", 3000);
<% end %>
        </script>
  </body>
</html>

app/views/listing/delete.html.erb
<h1>Listing#delete</h1>
<p>Find me in app/views/listing/delete.html.erb</p>

app/views/listing/edit.html.erb
<h1>Endre annonse</h1>

<%= form_for @listing, url: {action: :update} do |f| %>
  <% if @listing.errors.messages.length > 0 %>
    <div class="errors">
      <% @listing.errors.messages.each do |key, value| %>
        <% value.each do |message| %>
          <span class='error'><%= h key %> <%= h message %></span>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'materialize-textarea' %>

  <%= f.submit 'Endre annonse', class: 'btn' %>
<% end %>

app/views/listing/index.html.erb
<div class="section">
  <div class="row">
    <div class="col s12">
      <form method="GET" action='<%= listing_index_path %>'>
        <div class="card-panel">
          <div class="input-field" id='search-div'>
            <i class="material-icons prefix">search</i>
            <input type="text" value="<%= @search_query %>" id='query_string' name='sokeord'>
            <label for="query_string">Søk</label>
          </div>
        </div>
      </form>
    </div>
    <div class="col s12">
      <div class="row">
        <% if @listings.any? %>
          <%= render partial: 'shared/listing', collection: @listings, as: :listing %>
          <%= will_paginate @listings, param_name: :side,
            previous_label: 'Forrige', next_label: 'Neste' %>
        <% else %>
          <div class="listing-placeholder">
            <p class='grey-text'>Ingen annonser matcher ditt søk</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listing/new.html.erb
<h1>Lag en ny annonse</h1>

<%= form_for @listing, url: {action: :create} do |f| %>
  <% if @listing.errors.messages.length > 0 %>
    <div class="errors">
      <% @listing.errors.messages.each do |key, value| %>
        <% value.each do |message| %>
          <span class='error'><%= h @listing.class.human_attribute_name(key) %> <%= h message %></span>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <%= f.label :title, 'Tittel' %>
  <%= f.text_field :title, autofocus: true %>

  <%= f.label :price, 'Leiepris' %>
  <%= f.number_field :price, min: 0, max: 1000000 %>

  <%= f.label :description, 'Beskrivelse' %>
  <%= f.text_area :description, class: 'materialize-textarea', placeholder:
    'Her kan du skrive en kort beskrivelse av produktet ditt, hvor lenge du vil leie det ut og og hvilken tilstand produktet er i. (Eksempel: sort jakke fra H&M, leies ut i én uke, og er pent brukt.)' %>

  <div class="file-field input-field">
    <em class='grey-text image-disclaimer'>Du kan ikke endre bildene etter at de er lastet opp</em>
    <div class="btn">
      <span>Bilder</span>
      <%= f.file_field :listingimages, multiple: true %>
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text" placeholder="Last opp et eller fler bilder">
    </div>
  </div>

  <%= f.submit 'Opprett annonse', class: 'btn' %>
<% end %>

app/views/listing/show.html.erb
<%# this will be implanted with an image once the user clicks an image %>
<div id="imagemodal" class="modal">
  <div class="modal-content">
  </div>
</div>

<div class="row listing-detail">
  <div class="col s12 m8">
    <h2 class='listing-title'><%= @listing.title %></h2>
    <p class='listing-name grey-text'>Opprettet <%= @listing.created_at.strftime('%d/%m-%y') %> av <%= link_to full_name(@listing.user), profile_path(id: @listing.user.id) %></p>
    <div class="chip"><%= @listing.price %> kr</div>
    <p>
    <%= @listing.description %>
    </p>
    <div class="listing-images listing-images-mobile col s12 m4 hide-on-med-and-up">
      <% if @listing.listingimages.any? %>
        <% @listing.listingimages.each do |image| %>
          <%= image_tag image.url, class: 'listingimage responsive-img' %>
        <% end %>
      <% end %>
    </div>
    <strong>Kontaktinformasjon</strong>
    <br>
    <div class='listing-contactinfo'>
      <div><i class="material-icons">email</i> <%= @listing.user.email %></div>
      <div><i class="material-icons">phone</i> <%= @listing.user.telephone %></div>
    </div>
    <%= render partial: 'shared/map', locals: { place_id: @listing.user.place_id } %>
    <br>
    <% if current_user == @listing.user || (current_user && current_user.admin) %>
      <%= link_to 'Slett annonse', listing_path(@listing), method: :delete, class: 'white-text btn red' %>
    <% end %>
    <% if current_user == @listing.user %>
      <%= link_to 'Rediger annonse', edit_listing_path(@listing), class: 'btn' %>
    <% end %>
  </div>
  <div class="listing-images col s12 m4 hide-on-small-and-down">
    <% if @listing.listingimages.any? %>
      <div class="card-panel">
        <% @listing.listingimages.each do |image| %>
          <%= image_tag image.url, class: 'listingimage responsive-img' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      Released under the AGPL-v3.0 license
      <a class="right" href="https://www.fullstck.io">made by <strong>fullstck</strong></a>
    </div>
  </div>
</footer>

app/views/shared/_listing.html.erb
<div class="col s6 m3">
  <a href="<%= listing_path(listing) %>">
    <div class="listing z-depth-1">
      <% if listing.listingimages[0] %>
        <%= image_tag listing.listingimages[0].thumb.url %>
      <% else %>
        <%= image_tag 'filler_img.png' %>
      <% end %>
      <div class="price chip">
        <%= listing.price %> kr
      </div>
      <h5><%= listing.title %></h5>
    </div>
  </a>
</div>

app/views/shared/_map.html.erb
<div class="video-container">
  <iframe
     width=600
     height=450
     frameborder=0
     style='border:0;'
     src='https://www.google.com/maps/embed/v1/place?key=<%= ENV['GMAPS_API_KEY'] %>&q=place_id:<%= place_id %>'>
  </iframe>
</div>

app/views/shared/_navigation.html.erb
<nav>
  <div class="nav-wrapper container">
    <a href="<%= root_path %>">
      <% if controller_name != 'static_page' %>
        <img class="logo-image" src="<%= asset_path('logo.png') %>" alt="Logo">
      <% else %>
        <img class="logo-image" src="<%= asset_path('logo_white.png') %>" alt="Logo">
      <% end %>
    </a>
    <a class="brand-logo" href="<%= root_path %>">
      Leiestedet
    </a>

    <%# dropdown structure for the logged in user %>
    <ul id="dropdown-user-logged-in" class="dropdown-content">
      <li><%= link_to 'Profil', profile_path %></li>
      <li><%= link_to 'Rediger profil', edit_user_registration_path %></li>
      <li><%= link_to 'Logg ut', destroy_user_session_path, method: :delete %></li>
    </ul>

    <%# desktop navigation %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to 'Om oss', about_path %></li>
      <li><%= link_to 'Annonser', listing_index_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Ny annonse', new_listing_path %></li>
        <li><a class="dropdown-button" data-activates="dropdown-user-logged-in"><%= current_user.first_name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
        <li><%= link_to 'Logg inn', new_user_session_path %></li>
        <li><%= link_to 'Registrer deg', new_user_registration_path %></li>
      <% end %>
    </ul>

    <%# mobile navigation %>
    <ul id="nav-mobile" class="side-nav">
      <li><%= link_to 'Om oss', about_path %></li>
      <li><%= link_to 'Annonser', listing_index_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Ny annonse', new_listing_path %></li>
        <li><%= link_to 'Profil', profile_path %></li>
        <li><%= link_to 'Logg ut', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Logg inn', new_user_session_path %></li>
        <li><%= link_to 'Registrer deg', new_user_registration_path %></li>
      <% end %>
    </ul>

    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/static_page/about.html.erb
<div class="section">
  <h1>Leiestedet UB</h1>
  <p class="lead">Leiestedet er en nettside hvor du kan leie klaer.</p>
  <a class="btn" href="<%= listing_index_path %>">Se annonser</a>
</div>

app/views/static_page/index.html.erb
<div class="full-page-jumbotron">
  <div class="content">
    <h4>Hvorfor eie når du kan leie?</h4>
    <h5>
      Vi ønsker å bidra til en mer bærekraftig og miljøvennlig motebransje
      ved å senke kjøpepresset og utnytte de klærne vi allerede har.
    </h5>

    <%= link_to 'Registrer deg', new_user_registration_path, class: 'btn btn-large waves-effect' %>
  </div>
</div>

<div class='container'>
  <div id='about-us'>
    <h2>Om oss</h2>
    <div class="row">
      <div class="col s12 l9">
        <p class='flow-text'>
        Vi er en gruppe elever fra Elvebakken videregående skole som har startet
        en ungdomsbedrift, <i>Leiestedet</i>. <i>Leiestedet</i> er en løsning på
        kjøp og kast-forbruket av klær i dagens samfunn. Vi tilbyr en tjeneste
        hvor man kan leie og leie ut klær, og med dette ønsker vi en mer
        sosialt inkluderende og miljøvennlig klespolitikk.
        </p>
      </div>
    </div>
  </div>

  <div id='contact'>
    <%# shy is for breaking words on smaller screens, really nice! %>
    <h2>Kontakt&shy;informasjon</h2>
    <div class="row">
      <div class="col s12 l9">
        <p class="flow-text card-panel">
          Magnus Windelstad<br>
          <a href="mailto:leiestedetub@gmail.com">leiestedetub@gmail.com</a><br>
          97798971<br>
        </p>
        <%= render partial: 'shared/map', locals: { place_id: "ChIJq4FuGGRuQUYRGKaGfXsjSoI" } %>
      </div>
    </div>
  </div>
</div>